In [1]:
import numpy as np

### **[실습] 데이터를 기반으로 배열 연산 수행**

<aside>
❓

다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)
</aside>

In [5]:
# - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
# - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)

arr1 = np.array([200, 340, 150, 400])
arr2 = np.array([220, 300, 180, 420])
print(arr1.sum())
print(arr2.sum())

arr_total = np.array([arr1, arr2])
print(arr_total.mean(axis=0))

1090
1120
[210. 320. 165. 410.]



### **[실습 1] 기본 산술 연산**

<aside>
❓

다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.

</aside>

```python
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
```


In [7]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.divide(arr1, arr2))

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]



### [**실습 2] Dot Product**

### 1/21 전격 공개!!!!!

---

### [**실습 3] 브로드캐스팅**

### 1/21 전격 공개!!!!!

---



### **[실습 4] 비교 연산 및 집계 함수 사용**

<aside>
❓

1. 배열에서 20보다 큰 값을 찾아 출력하세요.
2. 배열의 합계, 최대값, 최소값, 평균을 계산하세요.
</aside>

```python
arr = np.array([10, 20, 30, 40, 50])
```

In [9]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 20])
print(arr.sum())
print(arr.max())
print(arr.min())
print(arr.mean())

[30 40 50]
150
50
10
30.0
