# ndarray Indexing & Slicing

In [1]:
import numpy as np

### 기본 indexing

In [ ]:
# 1차원 배열의 indexing
arr = np.arange(1, 11)
print(arr)
print(arr[6])
print(arr[-4])

[ 1  2  3  4  5  6  7  8  9 10]
7
7


In [ ]:
arr_2d = np.array([[10, 20, 30], [40, 50, 60]])
print(arr_2d)
print("========")

print(arr_2d[0])
print(arr_2d[0][2])
print(arr_2d[0, 2])
print(arr_2d[(0, 2)])

# 개인적으로 test
print(arr_2d[(-1, 2)]) # 맨 뒤 인덱스의 2차원 2번 인덱스 = 60

[[10 20 30]
 [40 50 60]]
[10 20 30]
30
30
30
60


In [ ]:
arr_2d = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])

print(arr_2d[1, 0])     # 44
print(arr_2d[2, 1])     # 88
print(arr_2d[-1, -2])   # 88 (음수 인덱스 활용하기)

44
88
88


### 기본 slicing

In [ ]:
# 1차원 배열 슬라이싱은 기본 list 슬라이싱과 똑같음!
arr = np.arange(1, 11)
print(arr)

print(arr[2:7]) # [3 4 5 6 7]
print(arr[::2]) # [1 3 5 7 9]
print(arr[4:]) # [5 6 7 8 9 10]
print(arr[:-3]) # [1 2 3 4 5 6 7]
print(arr[::-1]) # [10 9 8 7 6 5 4 3 2 1]

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6 7]
[1 3 5 7 9]
[ 5  6  7  8  9 10]
[1 2 3 4 5 6 7]
[10  9  8  7  6  5  4  3  2  1]


In [ ]:
# 2차원 배열 슬라이싱
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr_2d)
print(arr_2d[0:2, 1:2]) # [행 슬라이싱, 열 슬라이싱]
print('\n', arr_2d[0:2, :])
print()
print(arr_2d[0:2]) # 행 슬라이싱만 쓰면 열 전체를 슬라이싱
print(arr_2d[:, 1:]) # 행 전체를 슬라이싱하고 싶으면 , : 을 써야됨
print()
# 슬라이싱 = shape을 유지함 (차원 유지)
print(arr_2d[:-1, 0:1]) # 2차원 형태
print(arr_2d[:-1, 0:1].shape)
print()
# index 접근 = 인덱싱 -> 값을 꺼내서 반환 (차원 제거)
print(arr_2d[:-1, 0]) # 1차원 형태
print(arr_2d[:-1, 0].shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[20]
 [50]]

 [[10 20 30]
 [40 50 60]]

[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]
 [80 90]]

[[10]
 [40]]
(2, 1)

[10 40]
(2,)


### Fancy indexing

In [ ]:
# 1차원 배열의 fancy indexing
arr = np.arange(5, 31, 5)
print(arr)

indices = [1, 3, 5]
print(arr[indices]) # arr[[1, 3, 5]]

[ 5 10 15 20 25 30]
[10 20 30]


In [ ]:
# 2차원 배열의 fancy indexing
arr_2d = np.array([
    [5, 10, 15, 20]
    , [25, 30, 35, 40]
    , [45, 40, 55, 60]
])

print(arr_2d[[0,1],[1,2]]) # 0번째 행의 1번 열, 1번 행의 2번 열

[10 25]


### Boolean indexing

In [ ]:
arr = np.arange(1, 6)
bools = [True, False, False, False, True] # 1, 2, 3, 4, 5의 인덱스 T/F
print(arr[bools])

# 차원이 제거가 됨
print(arr[arr > 2])
print(arr[arr < 3])
print(arr[arr < 5])

[1 5]
[3 4 5]
[1 2]
[1 2 3 4]


In [ ]:
arr_2d = np.array([
    [3, 6, 9]
    , [12, 15, 18]
    , [21, 24, 27]
])

print(arr_2d[arr_2d > 10])
# print(arr_2d > 10) # boolean 배열 반환
print(arr_2d[arr_2d % 2 == 0])

[12 15 18 21 24 27]
[[False False False]
 [ True  True  True]
 [ True  True  True]]
[ 6 12 18 24]


##### [참고] np.all()
- np.all() : ndarray의 모든 요소가 조건을 만족할 때 True 반환
- np.any() : ndarray의 요소 중 하나라도 조건에 만족할 때 True를 반환

In [102]:
arr = np.array([10, 20, 30, 40, -50])

if np.all(arr > 0) :
    print('모든 수는 양수입니다.')
else :
    print('모든 수가 양수는 아닙니다.')

# all
print(np.all(arr > 0), type(np.all(arr > 0)))
# any
print(np.any(arr > 0), type(np.any(arr > 0)))

모든 수가 양수는 아닙니다.
False <class 'numpy.bool'>
True <class 'numpy.bool'>
