# ndarray 연산

In [1]:
import numpy as np

### 기본 연산
- 피연산자 두 배열의 같은 위치의 요소끼리 연산을 수행한 결과를 반환
- 피연산자가 되는 두 개의 배열은 같은 shape을 가져야 함

In [7]:
arr_a = np.arange(1, 10).reshape(3, 3) # 1차원 배열을 reshape으로 1차원 3개, 2차원 3개로 바꿔줌..
print(arr_a)

arr_b = np.full_like(arr_a, 7)
print(arr_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [8]:
# 덧셈
print(arr_a + arr_b)
print(np.add(arr_a, arr_b))

[[ 8  9 10]
 [11 12 13]
 [14 15 16]]
[[ 8  9 10]
 [11 12 13]
 [14 15 16]]


In [9]:
# 뺄셈
print(arr_a - arr_b)
print(np.subtract(arr_a, arr_b))

[[-6 -5 -4]
 [-3 -2 -1]
 [ 0  1  2]]
[[-6 -5 -4]
 [-3 -2 -1]
 [ 0  1  2]]


In [10]:
# 곱셈
print(arr_a * arr_b)
print(np.multiply(arr_a, arr_b))

[[ 7 14 21]
 [28 35 42]
 [49 56 63]]
[[ 7 14 21]
 [28 35 42]
 [49 56 63]]


In [11]:
# 나눗셈
print(arr_a / arr_b)
print(np.divide(arr_a, arr_b))

[[0.14285714 0.28571429 0.42857143]
 [0.57142857 0.71428571 0.85714286]
 [1.         1.14285714 1.28571429]]
[[0.14285714 0.28571429 0.42857143]
 [0.57142857 0.71428571 0.85714286]
 [1.         1.14285714 1.28571429]]


In [12]:
# 거듭제곱
print(arr_a ** arr_b)
print(np.power(arr_a, arr_b))

# 제곱
print(np.square(arr_a, arr_b))

# 제곱근
print(np.sqrt(arr_a))

[[      1     128    2187]
 [  16384   78125  279936]
 [ 823543 2097152 4782969]]
[[      1     128    2187]
 [  16384   78125  279936]
 [ 823543 2097152 4782969]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [13]:
# 몫 연산
print(arr_a // arr_b)
print(np.floor_divide(arr_a, arr_b))

[[1 0 0]
 [0 0 0]
 [0 0 0]]
[[1 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
# 나머지 연산
print(arr_a % arr_b)
print(np.mod(arr_a, arr_b))

[[0 2 3]
 [4 5 6]
 [7 8 9]]
[[0 2 3]
 [4 5 6]
 [7 8 9]]


---

### 연산 함수 및 집계 함수

In [15]:
arr_negative = np.array([[-1, -2], [-100, -200]])
arr_float = np.array([[1.234, 5.678], [3.14, 2.81]])
arr = np.arange(1, 7).reshape(2, 3) # 1~6까지의 수를 2행 3열로 만들기

In [16]:
# 절댓값 구하기
print(np.abs(arr_negative))

[[  1   2]
 [100 200]]


In [17]:
# 올림
print(np.ceil(arr_float))

[[2. 6.]
 [4. 3.]]


In [18]:
# 반올림
print(np.round(arr_float))
print(np.round(arr_float, 2)) # 소수점 2번째 자리까지 반올림 하라는 뜻

[[1. 6.]
 [3. 3.]]
[[1.23 5.68]
 [3.14 2.81]]


In [19]:
# 내림
arr_float = np.array([[1.234, -5.678], [-7.89, 10.123]])
print(np.trunc(arr_float)) # 버림(절삭)
print(np.floor(arr_float)) # 내림

[[ 1. -5.]
 [-7. 10.]]
[[ 1. -6.]
 [-8. 10.]]


In [26]:
print(arr)
# 최대값 / 최소값
print(np.max(arr))
print(arr.max())
print(np.min(arr))
print(arr.min())

print('==========')
print(np.max(arr, axis = 0))    # 행 기준 (행을 고정하고, 같은 열에서 가장 큰값)
print(np.min(arr, axis = 1))    # 열 기준 (열을 고정하고, 같은 행에서 가장 작은 값)

[[1 2 3]
 [4 5 6]]
6
6
1
1
[4 5 6]
[1 4]


In [27]:
# 합계
print(np.sum(arr))
print(arr.sum())
print('========')
print(arr.sum(axis=0)) # 행 기준 (행 방향 총합 덧셈)
print(arr.sum(axis=1)) # 열 기준 (열 방향 총합 덧셈)

21
21
[5 7 9]
[ 6 15]


In [28]:
# 평균! 헷갈림 주의
print(np.mean(arr))
print(arr.mean())
print('========')
print(arr.mean(axis=0)) # 행 기준
print(arr.mean(axis=1)) # 열 기준

3.5
3.5
[2.5 3.5 4.5]
[2. 5.]


### Broadcasting 연산

- 두 피연산자 (배열)의 shape이 다르면 broadcasting 연산을 수행한다.
- shape이 작은 쪽이 큰 쪽에 맞춰 확장한다.
- 두 배열의 행 또는 열이 일치해야 확장 가능하다.
- 크기가 1인 경우 무조건 확장 가능하다.
- shape이 다른 경우, 마지막 축부터 차원이 동일한지 비교한다.

In [ ]:
arr_a = np.arange(1, 10).reshape(3, 3) # 1차원 배열을 reshape으로 1차원 3개, 2차원 3개로 바꿔줌..

arr_b = np.full_like(arr_a, 5)
arr_b = np.array([5, 5, 5])     # shape = (3,) => (1,3)으로 앞 차원을 늘림!
arr_b = np.array([5])           # shape = (1,)
arr_b = 5                       # 스칼라값이라고 부름.

result = arr_a * arr_b
print(result)
print(result.shape)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
(3, 3)


In [17]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
arr2 = np.array([5, 10, 100])           # (3,)
print(arr1 * arr2)

[[  5  20 300]
 [ 20  50 600]]


In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
arr2 = np.array([[100], [200]])         # (2,1)
print(arr1 * arr2)

[[ 100  200  300]
 [ 800 1000 1200]]


In [ ]:
arr1 = np.array([1, 2, 3])          # (3,)
arr2 = np.array([[4], [5], [6]])    # (3, 1)
print(arr1 * arr2)

[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]


In [15]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
arr2 = np.array([1, 2])         # (2,)
# print(arr1 * arr2)

### 행렬 곱셈 (=점곱, 내적, Dot Product)

- [ 행렬 A @ 행렬 B ]
- 두 행렬 A, B의 곱셈은 첫 번째 행렬 A의 행과 두 번째 행렬 B의 열 간의 곱셈을 수행한다.
- 연산 결과의 shape은 행렬 A의 행 수, 행렬 B의 열 수 이다.
- 기호 : @

In [20]:
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[1, 2], [3, 4]])

# 기본 산술연산
print(arr_a * arr_b)
print(arr_a.shape, arr_b.shape, (arr_a * arr_b).shape)

# 내적
print(np.dot(arr_a, arr_b))
print(np.dot(arr_a, arr_b).dot)

[[ 1  4]
 [ 9 16]]
(2, 2) (2, 2) (2, 2)
[[ 7 10]
 [15 22]]
<built-in method dot of numpy.ndarray object at 0x0000021FAA26FF90>


In [23]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])        # (2, 3)
arr4 = np.array([[7, 8], [9, 10], [11, 12]])   # (3, 2)

print(np.dot(arr3, arr4))   # (2, 3) * (3, 2) = (2, 2)
print(np.dot(arr4, arr3))   # (3, 2) * (2, 3) = (3, 3)

[[ 58  64]
 [139 154]]
[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]


In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# print(arr @ arr)

In [ ]:
print(arr)

# arr.T = arr의 전치 행렬 (행, 열을 교환)
print(arr.T) # 원래 [[1, 2, 3], [4, 5, 6]] 이렇게 생긴애가 행 열이 바뀜!!
# print(arr @ arr.T)

# matmul() 내적 구하는 함수임.
# @ = matmul의 연산자
    # Dot Product와는 좀 다른거임.
    # 차원이 달라지면 동작 방식이 달라짐.
print(np.matmul(arr, arr.T))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]
