# ndarray 정렬

In [1]:
import numpy as np

In [2]:
# 1차원 배열 정렬
arr = np.random.randint(1, 11, 10)
arr

array([2, 9, 4, 7, 1, 5, 4, 1, 4, 8], dtype=int32)

In [7]:
# np.sort(arr): 정렬된 ndarray를 "반환" (원본 ndarray는 영향을 받지 않음)
print(np.sort(arr))
print(arr)

[1 1 2 4 4 4 5 7 8 9]
[2 9 4 7 1 5 4 1 4 8]


In [8]:
np.sort(arr)[::-1]

array([9, 8, 7, 5, 4, 4, 4, 2, 1, 1], dtype=int32)

In [11]:
# 2차원 배열 정렬
arr = np.random.randint(10, size=(3, 4))    # 0 이상 10 미만
arr

array([[1, 5, 3, 0],
       [9, 9, 5, 1],
       [7, 4, 6, 5]], dtype=int32)

In [12]:
print(np.sort(arr))     # 기본값 axis=1

[[0 1 3 5]
 [1 5 9 9]
 [4 5 6 7]]


In [13]:
print(np.sort(arr, axis=0)) # 행 방향 정렬 (같은 열 안에서 정렬)
print(np.sort(arr, axis=1)) # 열 방향 정렬 (같은 행 안에서 정렬)

[[1 4 3 0]
 [7 5 5 1]
 [9 9 6 5]]
[[0 1 3 5]
 [1 5 9 9]
 [4 5 6 7]]


In [15]:
# axis=None: 축 무시 (행/열 구분없이 모든 값 정렬)
print(np.sort(arr, axis=None))
print(np.sort(arr, axis=None).shape)

[0 1 1 3 4 5 5 5 6 7 9 9]
(12,)


### np.argsort()

- 배열의 값을 정렬했을 때, 각 값의 원래 인덱스를 반환
- 정렬할 때 어떤 순서로 값을 배치해야 하는지 알려주는 인덱스를 반환
- 배열의 값을 정렬한 후, 정렬된 순서에 해당하는 인덱스를 반환

In [16]:
arr = np.array([100, 400, 200, 300])
print(np.sort(arr))
print(np.argsort(arr))

[100 200 300 400]
[0 2 3 1]


In [20]:
names = np.array(['리사', '로제', '제니', '지수'])
album_sales = np.array([900, 870, 1000, 670])

# argsort() -> 앨범판매량이 많은 순으로 멤버 이름을 출력
sales_desc = np.argsort(album_sales)[::-1]
print(names[sales_desc])

['제니' '리사' '로제' '지수']


In [22]:
# 2차원 배열에서 argsort
arr = np.array([[2026, 1, 21], [14, 43, 12]])

print(np.argsort(arr))          # 기본값 axis=1
print(np.argsort(arr, axis=0))
print(np.argsort(arr, axis=1))

[[1 2 0]
 [2 0 1]]
[[1 0 1]
 [0 1 0]]
[[1 2 0]
 [2 0 1]]
