# ndarray 정렬

In [3]:
import numpy as np

In [ ]:
arr = np.array([2, 9, 4, 7, 1, 5, 4, 1, 4, 8])
print(np.sort(arr)) # np.sort : 정렬된 ndarray를 반환. 원본은 영향받지 않음.

array([1, 1, 2, 4, 4, 4, 5, 7, 8, 9])

In [6]:
np.sort(arr)[::-1]

array([9, 8, 7, 5, 4, 4, 4, 2, 1, 1])

In [8]:
# 2차원 배열 정렬
arr = np.random.randint(10, size=(3, 4))
arr

array([[0, 5, 3, 5],
       [3, 8, 5, 3],
       [1, 9, 9, 8]], dtype=int32)

In [ ]:
print(np.sort(arr)) # 같은 행 안에서만 정렬함.

[[0 3 5 5]
 [3 3 5 8]
 [1 8 9 9]]


In [11]:
print(np.sort(arr, axis=0)) # 행 방향 정렬 (같은 열 안에서 정렬)
print(np.sort(arr, axis=1)) # 열 방향 정렬 (같은 행 안에서 정렬)

[[0 5 3 3]
 [1 8 5 5]
 [3 9 9 8]]
[[0 3 5 5]
 [3 3 5 8]
 [1 8 9 9]]


In [14]:
# axis=None : 축 무시(행/열 구분없이 모든 값 정렬)
print(np.sort(arr, axis=None))
print(np.sort(arr, axis=None).shape)

[0 1 3 3 3 5 5 5 8 8 9 9]
(12,)


### np.argsort()

- 배열의 값을 정렬했을 때, 각 값의 원래 인덱스를 반환
- 정렬할 떄 어떤 순서로 값을 배치해야 하는지 알려주는 인덱스를 반환
- 배열의 값을 정렬한 후, 정렬된 순서에 해당하는 인덱스를 반환

In [15]:
arr = np.array([100, 400, 200, 300])
print(np.sort(arr))
print(np.argsort(arr))

[100 200 300 400]
[0 2 3 1]


In [ ]:
names = np.array(['리사', '로제', '제니', '지수'])
album_sales = np.array([900, 870, 1000, 670])

# 앨범 판매량이 많은 순으로 멤버 이름 출력
print(names[np.argsort(album_sales)][::-1])

['제니' '리사' '로제' '지수']


In [31]:
# 2차원 배열에서 argsort
arr = np.array([[2026, 1, 21], [14, 43, 12]])

print(np.argsort(arr))          # 기본값 axis=1
print(np.argsort(arr, axis=0))
print(np.argsort(arr, axis=1))

[[1 2 0]
 [2 0 1]]
[[1 0 1]
 [0 1 0]]
[[1 2 0]
 [2 0 1]]
