### ndarray 요소 추가 및 삭제

- ndarray는 고정 길이 배열 == 크기 변경이 불가 == 요소를 추가할 수 없음

In [1]:
import numpy as np

### np.insert()

- 원본 배열에서 요소가 추가된 새로운 배열을 반환

In [ ]:
# 1차원 배열에서 insert()
arr = np.array([10, 20, 30])

arr1 = np.insert(arr, 1, 15) # insert(원본배열, 삽입할 위치 인덱스, 삽입할 요소)
arr2 = np.append(arr, 100) # append(원본배열, 삽입할 요소)

# 기존에서 뭔가 추가되거나 delete된게 아님. 새로운 배열이 만들어진거임.
print(arr1)
print(arr2)
print(arr1 is arr)
print(arr2 is arr)

[10 15 20 30]
[ 10  20  30 100]
False
False


In [ ]:
# 2차원 배열에서 insert()
arr_2d = np.arange(1, 13).reshape(3, 4)
print(arr_2d)

print(np.insert(arr_2d, 1, 100)) # axis=None : 즉 무시 (1차원 배열로 변환 후 삽입)
print(np.insert(arr_2d, 1, 100).shape) # 차원 형식이 1차원이됨.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[  1 100   2   3   4   5   6   7   8   9  10  11  12]
(13,)


In [61]:
print(np.insert(arr_2d, 1, 999, axis=0))    # axis=0 : 행 기준
print(np.insert(arr_2d, 1, 999, axis=1))    # axis=1 : 열 기준
print(np.insert(arr_2d, 1, [999], axis=1))    # axis=1 : 열 기준
# print(np.insert(arr_2d, (1, ), [888, 999], axis=1))    # axis=1 : 열 기준
# print(np.insert(arr_2d, (1, 1, 1), [777, 888, 999], axis=1))    # axis=1 : 열 기준
print(np.insert(arr_2d, 1, [777, 888, 999], axis=1))    # axis=1 : 열 기준

[[  1   2   3   4]
 [999 999 999 999]
 [  5   6   7   8]
 [  9  10  11  12]]
[[  1 999   2   3   4]
 [  5 999   6   7   8]
 [  9 999  10  11  12]]
[[  1 999   2   3   4]
 [  5 999   6   7   8]
 [  9 999  10  11  12]]
[[  1 777   2   3   4]
 [  5 888   6   7   8]
 [  9 999  10  11  12]]


### np.delete()

- 원본 배열에서 요소를 삭제한 새로운 배열을 반환

In [ ]:
# 1차원 배열에서 delete()
arr = np.arange(0, 15)

# 기존에서 뭔가 추가되거나 delete된게 아님. 새로운 배열이 만들어진거임.
arr_del = np.delete(arr, 7) # delete(원본배열, 삭제할 위치 인덱스) 삭제할 인덱스의 위치 요소를 줌!
print(arr_del)
print(arr_del is arr)

[ 0  1  2  3  4  5  6  8  9 10 11 12 13 14]
False


In [45]:
# 2차원 배열에서 delete()
arr_2d = np.arange(1, 13).reshape(3, 4)
print(arr_2d)

print(np.delete(arr_2d, 1)) # axis=None이라서 1차원으로 변환이 됨.
print(np.delete(arr_2d, 1, axis=0))
print(np.delete(arr_2d, 1, axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]]


### ndarray 병합
- np.append()
- np.vstack()
- np.hstack()
- np.concatenate()

In [95]:
arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.arange(101, 113).reshape(3, 4)
arr1, arr2

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[101, 102, 103, 104],
        [105, 106, 107, 108],
        [109, 110, 111, 112]]))

### np.append()

In [67]:
print(np.append(arr1, arr2)) # axis = None
print(np.append(arr1, arr2).shape)

[  1   2   3   4   5   6   7   8   9  10  11  12 101 102 103 104 105 106
 107 108 109 110 111 112]
(24,)


In [68]:
print(np.append(arr1, arr2, axis=0))
print(np.append(arr1, arr2, axis=1))

[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [101 102 103 104]
 [105 106 107 108]
 [109 110 111 112]]
[[  1   2   3   4 101 102 103 104]
 [  5   6   7   8 105 106 107 108]
 [  9  10  11  12 109 110 111 112]]


### np.vstack () & np.hstack
- 병합 대상 ndarray를 튜플/리스트로 묶어서 전달해야함.

In [74]:
print(np.vstack([arr1, arr2]))      # axis=0 병합
print(np.hstack([arr1, arr2]))      # axis=1 병합

[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [101 102 103 104]
 [105 106 107 108]
 [109 110 111 112]]
[[  1   2   3   4 101 102 103 104]
 [  5   6   7   8 105 106 107 108]
 [  9  10  11  12 109 110 111 112]]


### np.concatenate()

In [ ]:
# append(), hstack(), vstack()과의 공통점/차이점
# => axis 설정 기본값이 무엇일지

# append() : 2차원인 경우 axis 설정을 해야 차원이 유지되며 병합됨
#   => axis의 기본설정값은 None임
# hstack(), vstack() : axis 설정을 하지 않아도 차원이 유지되며 병합됨
#   => hstack()는 axis=1
#   => vstack()는 axis=0

print(np.concatenate([arr1, arr2]))
print(np.concatenate([arr1, arr2], axis=1))

[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [101 102 103 104]
 [105 106 107 108]
 [109 110 111 112]]
[[  1   2   3   4 101 102 103 104]
 [  5   6   7   8 105 106 107 108]
 [  9  10  11  12 109 110 111 112]]


### ndarray 분할

##### np.split()

In [ ]:
arr = np.concatenate((arr1, arr2))

# split(원본배열, 분할할 개수, axis) / 기본값 axis=0
# arr_1, arr_2, arr_3 = np.split(arr, 3, axis=0)
arr_1, arr_2 = np.split(arr, 2, axis=0)
print(arr_1)
print(arr_2)
# print(arr_3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[101 102 103 104]
 [105 106 107 108]
 [109 110 111 112]]


In [ ]:
# 약수를 사용해서 분할할 개수를 정해야 함
# arr shape (6, 4)
n = 2
print(np.split(arr, n, axis=0)) # 행 기준(방향) -> 6행 : 1, 2, 3, 6
# print(np.split(arr, n, axis=1)) # 열 기준(방향) -> 4열 : 1, 2, 4

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[101, 102, 103, 104]]), array([[105, 106, 107, 108]]), array([[109, 110, 111, 112]])]
