# ndarray shape 변경

In [2]:
import numpy as np

### reshape()
- 요소의 개수가 맞는 shape으로 변형 가능(ndarray size는 유지)

In [16]:
arr = np.arange(12)
print(arr.shape)

arr = arr.reshape(3, 4)
arr = arr.reshape(1, 12)
arr = arr.reshape(6, 2)
# arr = arr.reshape(2, 7)   # 이런건 안됨
# arr = arr.reshape(8, 2)   # 이런건 안됨
print(arr, arr.shape)

arr = arr.reshape(3, 2, 2)
print(arr, arr.shape)

(12,)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] (6, 2)
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]] (3, 2, 2)


In [ ]:
# arr 이 (3, 2, 2) 일때
#  reshape(-1) == 1차원 처리
arr = arr.reshape(-1)
print(arr, arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)


In [21]:
# 여기까지의 arr : 1차원 (12,)
arr.shape

# shape의 요소 중 하나만 -1 == -1인 축은 자동으로 계산된다!
# 근데 약수중에 하나여야 된다! == 말이 돼야한다!!!!
arr = arr.reshape(4, -1)
arr = arr.reshape(-1, 6)
print(arr)
print(arr.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


### np.ravel()
- 1차원 변환

In [ ]:
arr = np.arange(50).reshape(5, 5, 2)
# print(arr) # 3차원 데이터
print(np.ravel(arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


### np.expand_dims()
- 깊이를 확장
- 차원을 추가해주는 함수

In [ ]:
arr_1d = np.arange(10)  # (10,)
print(np.expand_dims(arr_1d, axis=0).shape)   # (1, 10)
print(np.expand_dims(arr_1d, axis=1).shape)   # (10, 1)

(1, 10)
(10, 1)


In [37]:
arr_2d = np.arange(10).reshape(5, 2)
print(np.expand_dims(arr_2d, axis=0))
print(np.expand_dims(arr_2d, axis=1))

[[[0 1]
  [2 3]
  [4 5]
  [6 7]
  [8 9]]]
[[[0 1]]

 [[2 3]]

 [[4 5]]

 [[6 7]]

 [[8 9]]]


In [36]:
arr_2d = np.array([[1, 2], [3, 4]])
print(np.expand_dims(arr_2d, axis=0))
print(np.expand_dims(arr_2d, axis=1))
print(np.expand_dims(arr_2d, axis=2))

[[[1 2]
  [3 4]]]
[[[1 2]]

 [[3 4]]]
[[[1]
  [2]]

 [[3]
  [4]]]


### np.squeeze()
- 차원의 값(size)이 1일 때 제거<br>
(+) np.squeeze()는 axis를 지정하지 않으면 차원 값이 1인 걸 다 제거하는 구나..<br>
(+) np.squeeze()에서 차원 값이 1이라도 남기고 싶으면, axis를 특정 차원으로 지정햐야되겠구나..

In [19]:
arr = np.array([[1, 2]]) # (1, 2)
print(arr.shape)

arr_sq = np.squeeze(arr)
arr_sq = np.squeeze(arr, axis=0)
# arr_sq = np.squeeze(arr, axis=1)
print(arr_sq, arr_sq.shape)

(1, 2)
[1 2] (2,)


In [21]:
arr = np.array([[[1, 2]]]) # (2, 1)
print(arr.shape)

arr_sq = np.squeeze(arr)
arr_sq = np.squeeze(arr, axis=0)
arr_sq = np.squeeze(arr, axis=1)
print(arr_sq, arr_sq.shape)

(1, 1, 2)
[[1 2]] (1, 2)
