### **[실습 1] 1차원 배열 정렬**

<aside>
❓

다음 1차원 배열을 오름차순 및 내림차순으로 정렬하세요.

</aside>

```python
arr = np.array([50, 10, 30, 40, 20])
```

In [5]:
import numpy as np
arr = np.array([50, 10, 30, 40, 20])

print(np.sort(arr))
print(np.sort(arr)[::-1])

[10 20 30 40 50]
[50 40 30 20 10]


### [**실습 2] 2차원 배열 축 기준 정렬**

<aside>
❓

다음 2차원 배열을 행과 열을 기준으로 각각 정렬하세요.

</aside>

```python
arr2d = np.array([[8, 3, 5], [2, 9, 1]])
```

In [6]:
arr2d = np.array([[8, 3, 5], [2, 9, 1]])

print(np.sort(arr2d))
print(np.sort(arr2d, axis=0))

[[3 5 8]
 [1 2 9]]
[[2 3 1]
 [8 9 5]]


### **[실습 3] 인덱스를 반환하는 정렬**

<aside>
❓

다음 1차원 배열에서 정렬된 결과의 인덱스를 반환하고, 그 인덱스를 사용하여 배열을 정렬하세요.

</aside>

```python
arr = np.array([15, 10, 20])
```

In [8]:
arr = np.array([15, 10, 20])

print(arr[np.argsort(arr)])

[10 15 20]
