<aside>
❓

다음은 5개 지점에서 판매된 과일에 대한 월별 판매량 데이터입니다. 이 데이터는 각 지점의 판매량을 월별로 나타내며, 각 지점에서 판매된 사과, 바나나, 오렌지의 판매량이 기록되어 있습니다. 이 데이터를 사용하여 여러 가지 통계적 분석과 배열 조작을 수행하세요.

1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.
4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.
</aside>

In [35]:
import numpy as np
    
fruits = np.array(['사과', '바나나', '오렌지'])
# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
        [100, 140, 170, 190, 160, 180],  # 바나나 판매량
        [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
        [60, 70, 90, 100, 110, 95],
        [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
        [110, 120, 130, 150, 140, 160],
        [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
        [90, 100, 110, 120, 130, 125],
        [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
        [70, 85, 100, 110, 105, 95],
        [60, 90, 110, 100, 90, 95]]
])

# 1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
# 2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
# 3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.
# 4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.
# axis 0 : 지점 5개
# axis 1 : 과일 3개
# axis 2 : 6개월

# 사 바 오 월별 평균
month_mean = np.mean(sales_data, axis=2)
print('1번\n', np.round(month_mean))

# 각 월마다 뭐가 제일 많이 팔렸는지?
total_sales_per_month = np.sum(sales_data, axis=0)
max_sales_per_month = np.max(total_sales_per_month, axis=0) # 각 월마다 과일 판매량
max_sales_indices = np.argmax(total_sales_per_month, axis=0)
print('2번\n', fruits[max_sales_indices])

# 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.
# arr3 = np.max((np.sort(sales_data, axis=2)), axis=0)
total_sales_per_fruits = np.sum(sales_data, axis=(0,2))
print('3번\n사과 바나나 오렌지의 전체 판매량 :', total_sales_per_fruits)
print(fruits[np.argmax(total_sales_per_fruits)])

# 4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.
high_sales_data = sales_data[sales_data >= 150]
print('판매량이 150개 이상인 판매량 자체 (지점과 과일은 알지 못함) :',high_sales_data)

high_sales_idx = np.where(sales_data >= 150)

for i in range(high_sales_idx[0].size) : 
    spot = high_sales_idx[0][i] + 1
    fruit = high_sales_idx[1][i]
    fruit_name = fruits[fruit]
    month = high_sales_idx[2][i] + 1
    print(f'{spot}지점 | {fruit_name} | {month}월 => {high_sales_data[i]}개')

1번
 [[182. 157. 132.]
 [112.  88.  86.]
 [162. 135. 120.]
 [148. 112. 115.]
 [120.  94.  91.]]
2번
 ['사과' '사과' '사과' '사과' '사과' '사과']
3번
사과 바나나 오렌지의 전체 판매량 : [4340 3515 3260]
사과
판매량이 150개 이상인 판매량 자체 (지점과 과일은 알지 못함) : [150 200 230 180 210 170 190 160 180 160 150 160 180 170 190 150 160 150
 170 160 180]
1지점 | 사과 | 2월 => 150개
1지점 | 사과 | 3월 => 200개
1지점 | 사과 | 4월 => 230개
1지점 | 사과 | 5월 => 180개
1지점 | 사과 | 6월 => 210개
1지점 | 바나나 | 3월 => 170개
1지점 | 바나나 | 4월 => 190개
1지점 | 바나나 | 5월 => 160개
1지점 | 바나나 | 6월 => 180개
1지점 | 오렌지 | 3월 => 160개
1지점 | 오렌지 | 6월 => 150개
3지점 | 사과 | 3월 => 160개
3지점 | 사과 | 4월 => 180개
3지점 | 사과 | 5월 => 170개
3지점 | 사과 | 6월 => 190개
3지점 | 바나나 | 4월 => 150개
3지점 | 바나나 | 6월 => 160개
4지점 | 사과 | 3월 => 150개
4지점 | 사과 | 4월 => 170개
4지점 | 사과 | 5월 => 160개
4지점 | 사과 | 6월 => 180개
